### ISSUE TITLE
Find failed

### ISSUE THREAD

**Issue by maurelian** [sachaos/todoist#7]
After installing, and adding my Todoist API key, `todoist list` has empty output. `todoist add` and `todoist sync` both return something like this: 

```
panic: Find Failed

goroutine 1 [running]:
github.com/sachaos/todoist/lib.(*Sync).ConstructItemOrder(0xc420118380)
	/Users/primary/go/src/github.com/sachaos/todoist/lib/sync.go:97 +0x79d
github.com/sachaos/todoist/lib.SyncAll(0xc42001bf80, 0x28, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/primary/go/src/github.com/sachaos/todoist/lib/sync.go:113 +0x337
main.Sync(0xc4200d08c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/primary/go/src/github.com/sachaos/todoist/sync.go:11 +0xa4
main.main.func12(0xc4200d08c0, 0x0, 0xc4200d08c0)
	/Users/primary/go/src/github.com/sachaos/todoist/main.go:224 +0x43
github.com/urfave/cli.HandleAction(0x13e66a0, 0x1484298, 0xc4200d08c0, 0xc42006c600, 0x0)
	/Users/primary/go/src/github.com/urfave/cli/app.go:485 +0xd4
github.com/urfave/cli.Command.Run(0x1469e41, 0x4, 0x0, 0x0, 0xc4201144f0, 0x1, 0x1, 0x146e623, 0xa, 0x0, ...)
	/Users/primary/go/src/github.com/urfave/cli/command.go:207 +0xb6e
github.com/urfave/cli.(*App).Run(0xc4200ecea0, 0xc42000c3c0, 0x2, 0x2, 0x0, 0x0)
	/Users/primary/go/src/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/Users/primary/go/src/github.com/sachaos/todoist/main.go:232 +0x14f2
```

**Comment by sachaos** [comment]
Thank your report.
I'll investigate the problem.

**Comment by sachaos** [comment]
@maurelian 
The problem seems some task have invalid project ID.
It seems cause from sync error or something.

I fixed the problem by accepting invalid project id.
Might you try adapting this patch? #8

If this patch solve your problem, I'll merge to master.
