### ISSUE TITLE
panic when run without sync

### ISSUE THREAD

**Issue by xdg** [sachaos/todoist#98]
I didn't see at first that I needed to run `todoist sync`, so started with `todoist list` and got a panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x14310dc]

goroutine 1 [running]:
main.List.func1(0x0, 0x0)
        /private/tmp/todoist-20191021-98168-790l64/todoist-0.14.0/src/github.com/sachaos/todoist/list.go:40 +0xfc
main.traverseItems(0x0, 0xc000110f30, 0x0)
        /private/tmp/todoist-20191021-98168-790l64/todoist-0.14.0/src/github.com/sachaos/todoist/list.go:9 +0x3e
main.List(0xc0000c26e0, 0x0, 0x0)
        /private/tmp/todoist-20191021-98168-790l64/todoist-0.14.0/src/github.com/sachaos/todoist/list.go:35 +0x2d5
github.com/urfave/cli.HandleAction(0x148b560, 0x15485b0, 0xc0000c26e0, 0xc00006e800, 0x0)
        /private/tmp/todoist-20191021-98168-790l64/todoist-0.14.0/.brew_home/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x1528a9c, 0x4, 0x0, 0x0, 0xc000059320, 0x1, 0x1, 0x152bf88, 0xe, 0x0, ...)
        /private/tmp/todoist-20191021-98168-790l64/todoist-0.14.0/.brew_home/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x991
github.com/urfave/cli.(*App).Run(0xc000095380, 0xc00000e0c0, 0x2, 0x2, 0x0, 0x0)
        /private/tmp/todoist-20191021-98168-790l64/todoist-0.14.0/.brew_home/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6ab
main.main()
        /private/tmp/todoist-20191021-98168-790l64/todoist-0.14.0/src/github.com/sachaos/todoist/main.go:262 +0x160e
```

I synced and the problem went away, but it's not a great first experience if someone misses the need to sync first.

**Comment by bdlangton** [comment]
I wondered what was going on. Thanks for this! I had the same panic, but no longer after I ran sync. I had used this app long ago, and I left it installed but went awhile without using it.

**Comment by kenliu** [comment]
I'm closing this because I don't believe this happens anymore on the latest versions.
